= Top 20 I/O Wait nodes

Jasper Report template for OpenNMS which shows the top 20 nodes with highest I/O wait.

== Requirements

* Report requires to have `storeByForeignSource=true`
* _Statsd_ needs to be enabled in `service-configuration.xml`

== Install

.Step 1
Download the report template into OpenNMS report template directory
[source, bash]
----
cd ${OPENNMS_HOME}/etc/report-templates
wget https://raw.githubusercontent.com/opennms-forge/jasper-reports-top-io-wait/master/TopIOWait.jrxml
----

.Step 2
Register a new database report in `database-reports.xml`

[source, xml]
----
<report id="Top20-IOWait" display-name="TOP 20 nodes by I/O Wait" online="true" report-service="jasperReportService" description="TOP 20 nodes by I/O Wait" />
----

.Step 3
Assign report to be executed with the built-in JasperReport engine

[source, xml]
----
<report id="Top20-IOWait" template="TopIOWait.jrxml" engine="jdbc" />
----

.Step 4
Create TopN data extraction with _Statsd_ in `statsd-configuration.xml`.
The example package below gathers TopN data every day 17:10 and keeps it in the database for 30 days.

[source, xml]
----
<package name="IOWAITReports">
    <packageReport name="TopN_IOWait" description="Top 20 iowait across all nodes"
                   schedule="0 17 10 * * ?" retainInterval="2592000000"
                   status="off">
        <parameter key="count" value="20"/>
        <parameter key="consolidationFunction" value="AVERAGE"/>
        <parameter key="relativeTime" value="YESTERDAY"/>
        <parameter key="resourceTypeMatch" value="nodeSnmp"/>
        <parameter key="attributeMatch" value="CpuRawWait"/>
    </packageReport>
</package>
----
.Step 5

The changes in `statsd-configuration.xml` require a restart of _OpenNMS_.
As soon the first TopN run populate the database the JasperReport can be used.

[source, bash]
----
# On systems using Systemd
systemctl restart opennms

# On systems with legacy init environment
service opennms restart
----
